name: DeployIAC

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # deploy-iac
  deploy-iac:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - name: 'Login via Azure CLI'
       uses: azure/login@v2
       with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
     - shell: bash
       run: |
            # Provision IaC
            chmod +x ./SemKernel/deploy.sh
            cd SemKernel
            ./deploy.sh

